
@baseUrl = https://us-central1-exercise4-41e1b.cloudfunctions.net/api

### Example of endpoints for basic CRUD operations.
#    Later in your submission, leave only the one that you actually use and remove others from this file.


### Get the list of quotes
GET {{baseUrl}}/quotes

###  Getting a quote for a given id
GET {{baseUrl}}/quotes/DG7ypE02TnjXb2cRfRSW

###  Add a new quote
POST {{baseUrl}}/quotes
Content-Type: application/json

{
    "data": "This is a new quote",
    "like" : 0,
    "dislike" : 0
}

### Update a quote partly
PATCH {{baseUrl}}/quotes/U6A7xpvOMiGy1ZahlZDa
Content-Type: application/json

{
        "like" : 10
}

###
PATCH {{baseUrl}}/quotes/U6A7xpvOMiGy1ZahlZDa
Content-Type: application/json

{
        "dislike" : 2
}

### Replace an existing quote entirely
PUT {{baseUrl}}/quotes/U6A7xpvOMiGy1ZahlZDa
Content-Type: application/json

{
    "data": "Programming is not everything",
    "like" : 5,
    "dislike" : 5
}

### Delete a quote
DELETE {{baseUrl}}/quotes/U6A7xpvOMiGy1ZahlZDa

### Thumb up (or Like) - Update the 'like' attribute by inreasing by 1
PATCH {{baseUrl}}/quotes/dhsYzlCuOyZE4xEfmOgc/like

###
PATCH {{baseUrl}}/like/dhsYzlCuOyZE4xEfmOgc

###
PATCH {{baseUrl}}/quotes/dhsYzlCuOyZE4xEfmOgc?vote=like